version: "2"

x-op-network: &network
  networks:
    - pepeg-net

services:
  trainer:
    container_name: pepeg-bot-trainer
    image: ghcr.io/rahagi/pepeg-bot2:latest
    entrypoint: "/app/pepeg-bot train"
    <<: *network
    env_file:
      - .env
    volumes:
      - ./training:/training

networks:
  pepeg-net:
    driver: bridge
