name: "Check & Publish"

on:
  push:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'dumper:')"
    steps:
      - name: Declare Variables
        id: vars
        run: |
          echo ::set-output name=SHA8::$(echo ${GITHUB_SHA::8})
          echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
          echo ::set-output name=DOCKER_TAG::$([[ $GITHUB_REF_TYPE == "tag" ]] && echo "latest" || echo "dev")
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.DOCKER_TAG }}
          build-args: |
            VERSION=${{ steps.vars.outputs.VERSION }}-${{ steps.vars.outputs.SHA8 }}
